apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $SANDBOX
  namespace: teko-system
spec:
  project: default
  source:
    path: .
    repoURL: 'https://git.teko.vn/workloads/test-argo.git'
    targetRevision: HEAD
    plugin:
      name: helmfile-sandbox
      env:
        - name: SANDBOX
          value: $SANDBOX
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
