apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argo
  namespace: teko-system
spec:
  project: default
  source:
    path: .
    repoURL: 'https://git.teko.vn/workloads/test-argo.git'
    targetRevision: HEAD
    plugin:
      name: helmfile-sandbox
      env:
        - name: ENVIRONMENT
          value: a
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
