releases:
# - name: echo-service
#   values:
#   - namespace.yaml
#   chart: teko/teko-backend-v3
- name: echo
  namespace: echo-service-2
  forceNamespace: echo-service-2
  missingFileHandler: Warn
  values:
  - echo.yaml.gotmpl
  - ./{{ env "SANDBOX" }}/echo.yaml
  chart: teko/teko-backend-v2
