fullnameOverride: "app-hello-python"
replicaCount: 1

image:
  repository: asia.gcr.io/teko-registry/sre/toandn-demo-sandbox
  pullPolicy: IfNotPresent
  tag: "m-b0597d31"


podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
  hosts:
    - host: app-hello.a.teko.vn
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: teko-tls
      hosts:
      - app-hello.a.teko.vn

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}