releases:
- name: echo-service
  values:
  - namespace.yaml
  chart: teko/teko-backend-v3
- name: echo
  namespace: echo-service
  forceNamespace: echo-service
  values:
  - echo.yaml.gotmpl
  chart: teko/teko-backend-v2
