#!/bin/bash

# adapt script kubectl secret
sed -i "s/cut -d\"\/\" -f3/rev | cut -d\"\/\" -f1 | rev/g" /usr/bin/kubectl-secret

envs='envs'

for FILE in $(git diff --name-only $CI_COMMIT_SHA $CI_COMMIT_BEFORE_SHA | grep  "./__secrets"); do
  export ENV="dev"
  export PROJECT=$(echo $FILE | cut -d"/" -f1)
  SECRET_FOLDER=$(echo $FILE | rev | cut -d"/" -f2 | rev)
  if [ "$SECRET_FOLDER" == "__secrets" ]; then
    while read environment; do
      export NAMESPACE=$environment-$(echo $FILE | cut -d"/" -f1)
      echo "1: kubectl secret $FILE"
      kubectl secret $FILE
    done < $envs

    extend_envs=$(find ./$PROJECT/* -type d | rev | cut -d "/" -f1 | rev | grep -v "__secrets")
    for extend_env in $extend_envs; do
      export NAMESPACE=$extend_env-$(echo $FILE | cut -d"/" -f1)
      echo "2: kubectl secret $FILE"
      kubectl secret $FILE
    done
  else
    export NAMESPACE=$SECRET_FOLDER-$(echo $FILE | cut -d"/" -f1)
    echo "3: kubectl secret $FILE"
    kubectl secret $FILE
  fi
done
