#!/bin/bash

envs='envs'

# adapt script kubectl secret
sed -i "s/cut -d\"\/\" -f3/rev | cut -d\"\/\" -f1 | rev/g" /usr/bin/kubectl-secret


for DIR in $(ls -d */ | grep -v '_cloudrun\|_scripts\|_gateway\|_acl'); do
  while read environment; do
    echo Applying in namespace $environment-$DIR ...
    export PROJECT=$(echo $DIR | cut -d"/" -f1)
    export NAMESPACE=$environment-$(echo $DIR | cut -d"/" -f1)
    if [ -d "$PROJECT/__secrets" ]; then
      for FILE in $(ls $PROJECT/__secrets/ ); do
        if [ -f "$PROJECT/__secrets/$FILE" ]; then
          echo "kubectl secret $PROJECT/__secrets/$FILE"
          kubectl secret $PROJECT/__secrets/$FILE
        fi
      done
    fi
  done < $envs

  extend_envs=$(find ./$PROJECT/* -type d | rev | cut -d "/" -f1 | rev | grep -v "__secrets")
  for environment in $extend_envs; do
    echo Applying in namespace $environment-$DIR ...
    export PROJECT=$(echo $DIR | cut -d"/" -f1)
    export NAMESPACE=$environment-$(echo $DIR | cut -d"/" -f1)
    for FILE in $(ls $PROJECT/__secrets/$environment ); do
      if [ -f "$PROJECT/__secrets/$environment/$FILE" ]; then
        echo "kubectl secret $PROJECT/__secrets/$environment/$FILE"
        kubectl secret $PROJECT/__secrets/$environment/$FILE
      fi
    done
  done
done

for DIR in $(kubectl get namespaces --no-headers | awk '{print $1}'); do
  echo Applying in namespace $DIR ...
  export NAMESPACE=$DIR
  for FILE in $(ls _scripts/_all); do
    echo "kubectl secret _scripts/_all/$FILE"
    kubectl secret _scripts/_all/$FILE
  done
done
