#!/bin/bash

set -e

NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'de 
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

IMAGE_REPOSITORY=$(echo ${CI_COMMIT_MESSAGE} | sed -n "s/^Teko auto release \(.*\):.*/\1/p")

git --no-pager diff HEAD~1

for rl in $(teko releases -i $IMAGE_REPOSITORY)
do
    upgrade_command=$(teko upgrade -r $rl -o command)
    echo -e "${GREEN}❯❯❯ ${upgrade_command}${NOCOLOR}"
    eval ${upgrade_command}
done
