#!/usr/bin/python3

import yaml
import os
import sys

with open("sandboxes.yaml") as stream:
    try:
        sandboxes = yaml.safe_load(stream)['sandboxes']
        f = open("envs", "w")
        for sandbox in sandboxes:
            sandbox_name = sandbox['name']
            deploy_all = sandbox['deploy-all']
            # set environment variables
            if deploy_all:
              f.write(f"{sandbox_name}\n")
            else:
              #TO DO: add deploy some services not all
              print("Nothing to do with " + sandbox_name)
        f.close()
    except yaml.YAMLError as exc:
        print(exc)
