#!/bin/bash

set -e

NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'


if [[ "$GITLAB_USER_LOGIN" == "teko-bot" ]];
then
    msg=$(git log --pretty=format:"%s" -n 1 | awk '{print $4}' | cut -d'/' -f3-)
    echo $msg
    curl -i -XPOST 'http://events-influxdb.teko-system:8086/write?db=teko_events' --data-binary "deploy,app=\"deploy\" msg=\"$msg\""
else
    fc=$(git diff $(git log --pretty=format:"%h" -n 1) HEAD~1 --name-only | cut -d'/' -f1 | uniq)
    msg="Author: $GITLAB_USER_LOGIN, Type: Update, Proj: $fc"
    echo $msg
    curl -i -XPOST 'http://events-influxdb.teko-system:8086/write?db=teko_events' --data-binary "deploy,app=\"deploy\" msg=\"$msg\""
fi