#!/bin/bash

envs='envs'

find . -name '*.yaml' -exec cp {} {}.gotmpl \;
find **/ -name 'helmfile.yaml' -exec cp {} {}.raw \;

root_dir=`pwd`

set -e

NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'


if [[ "$CI_COMMIT_BEFORE_SHA" == '0000000000000000000000000000000000000000' ]];
then
    echo -e "${RED}[WARN] last run commit id is not found, run upgrade for last 10 commit${NOCOLOR}"
    git diff --name-only HEAD~10 | teko upgraded-lookup | while read line
    do
        echo -e "${GREEN}❯❯❯ ${line}${NOCOLOR}"
        eval "${line}"
    done
else
    echo -e "${ORANGE}[INFO] upgrade to last commit ${CI_COMMIT_BEFORE_SHA}${NOCOLOR}"
    git --no-pager diff $CI_COMMIT_BEFORE_SHA
    git diff --name-only $CI_COMMIT_BEFORE_SHA | grep -v '__secrets/' | grep -v '_scripts/' | while read line
    do
      echo $line
      while read environment; do
        find **/ -name 'helmfile.yaml.raw' -exec sh -c 'cp {} $(dirname "{}")/helmfile.yaml' \;
        find **/ -name 'helmfile.yaml' -exec sed -i "s/namespace: /namespace: ${environment}-/g" {} \;
        find **/ -name 'helmfile.yaml' -exec sed -i "s/yaml/yaml.gotmpl/g" {} \;
        export ENVIRONMENT=$environment
        echo $ENVIRONMENT
        dir=$(dirname "${line}")
        cd $dir
        cat helmfile.yaml
        helmfile apply --context=3 --skip-deps
        cd $root_dir
      done < $envs
      
      find **/ -name 'helmfile.yaml.raw' -exec sh -c 'cp {} $(dirname "{}")/helmfile.yaml' \;
      
      project=$(dirname $line)
      echo $project
      extend_envs=$(find ./$project/* -type d | rev | cut -d "/" -f1 | rev | grep -v "__secrets" | grep -v '_scripts/')
      for extend_env in $extend_envs; do
        find **/ -name 'helmfile.yaml.raw' -exec sh -c 'cp {} $(dirname "{}")/helmfile.yaml' \;
        find **/ -name 'helmfile.yaml' -exec sed -i "s/namespace: /namespace: ${extend_env}-/g" {} \;
        find **/ -name 'helmfile.yaml' -exec sed -i "s/yaml/yaml.gotmpl/g" {} \;
        export ENVIRONMENT=$extend_env
        echo $ENVIRONMENT
        dir=$(dirname "${line}")
        cd $dir 
        helmfile apply --context=3 --skip-deps
        cd $root_dir
      done
      find **/ -name 'helmfile.yaml.raw' -exec sh -c 'cp {} $(dirname "{}")/helmfile.yaml' \;
    done
fi
